services:
  flask_app:
    image: sy3079/flask-app:latest
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - data:/db

volumes:
  data: